### ISSUE TITLE
Runtime exception - 3/30 Runtime and File Kareo_SummaryOfCare_export_Joey_Miller

### ISSUE THREAD

**Issue by KenLord** [MDMI/MDMI#62]
Using the above running isomorphically, I get a runtime exception with the  message  below.  If I take out the medication section of the source file, it executes.

Error: org.openhealthtools.mdht.mdmi.MdmiException
Message: Error proccessing node ClinicalDocument

Caused by:
Error: org.openhealthtools.mdht.mdmi.MdmiException
Message: Error proccessing node ClinicalDocument/component/structuredBody

Caused by:
Error: org.openhealthtools.mdht.mdmi.MdmiException
Message: Error proccessing node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]

Caused by:
Error: org.openhealthtools.mdht.mdmi.MdmiException
Message: Error proccessing node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]/entry/substanceAdministration[@moodCode="EVN" and templateId[@root='2.16.840.1.113883.10.20.22.4.16']]

Caused by:
Error: org.openhealthtools.mdht.mdmi.MdmiException
Message: Error proccessing node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]/entry/substanceAdministration[@moodCode="EVN" and templateId[@root='2.16.840.1.113883.10.20.22.4.16']]/doseQuantity

Caused by:
Error: org.openhealthtools.mdht.mdmi.MdmiException
Message: Invalid mapping for node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]/entry/substanceAdministration[@moodCode="EVN" and templateId[@root='2.16.840.1.113883.10.20.22.4.16']]/doseQuantity

org.openhealthtools.mdht.mdmi.MdmiException: Error proccessing node ClinicalDocument
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:370)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:205)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getElements(DefaultSemanticParser.java:195)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.buildSemanticModel(DefaultSemanticParser.java:97)
	at org.openhealthtools.mdht.mdmi.engine.MdmiUow.processInboundSourceMessage(MdmiUow.java:150)
	at org.openhealthtools.mdht.mdmi.engine.MdmiUow.run(MdmiUow.java:78)
	at org.openhealthtools.mdht.mdmi.engine.MdmiEngine.executeTransfer(MdmiEngine.java:54)
	at org.openhealthtools.mdht.mdmi.Mdmi.exec(Mdmi.java:324)
	at org.openhealthtools.mdht.mdmi.Mdmi.executeTransfer(Mdmi.java:220)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain.onExecuteTransfer(FrmMain.java:625)
	at org.openhealthtools.mdht.mdmi.testui.FrmMain$9.actionPerformed(FrmMain.java:744)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.openhealthtools.mdht.mdmi.MdmiException: Error proccessing node ClinicalDocument/component/structuredBody
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:370)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:205)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:353)
	... 47 more
Caused by: org.openhealthtools.mdht.mdmi.MdmiException: Error proccessing node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:370)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:205)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:353)
	... 49 more
Caused by: org.openhealthtools.mdht.mdmi.MdmiException: Error proccessing node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]/entry/substanceAdministration[@moodCode="EVN" and templateId[@root='2.16.840.1.113883.10.20.22.4.16']]
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:370)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:205)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:353)
	... 51 more
Caused by: org.openhealthtools.mdht.mdmi.MdmiException: Error proccessing node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]/entry/substanceAdministration[@moodCode="EVN" and templateId[@root='2.16.840.1.113883.10.20.22.4.16']]/doseQuantity
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:370)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getMappedElement(DefaultSemanticParser.java:205)
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:353)
	... 53 more
Caused by: org.openhealthtools.mdht.mdmi.MdmiException: Invalid mapping for node ClinicalDocument/component/structuredBody/component/section[templateId[@root='2.16.840.1.113883.10.20.22.2.1.1']]/entry/substanceAdministration[@moodCode="EVN" and templateId[@root='2.16.840.1.113883.10.20.22.4.16']]/doseQuantity
	at org.openhealthtools.mdht.mdmi.engine.DefaultSemanticParser.getStructElement(DefaultSemanticParser.java:363)
	... 55 more

**Comment by KenLord** [comment]
resolved
